---
- name: MikroTik CHR Setup
  hosts: routers
  gather_facts: false
  tasks:

    - name: Set CHR login/password
      community.routeros.command:
        commands:
          - /user add name=newuser group=read password=password

    - name: Configure NTP client
      community.routeros.command:
        commands:
          - /system ntp client set enabled=yes servers=pool.ntp.org

    - name: Create loopback
      community.routeros.command:
        commands:
          - /interface bridge add name=loopback0

    - name: Add ip to loopback
      community.routeros.command:
        commands:
          - "/ip address add address={{ router_id }}/32 interface=loopback0"
    - name: Set routerID to ospf
      community.routeros.command:
        commands:
          - "/routing ospf instance add name=v2inst version=2 router-id={{ router_id }}"

    - name: Add ospf network to backbone
      community.routeros.command:
        commands:
          - /routing ospf area add name=bbone area-id=0.0.0.0 instance=v2inst

    - name: Add template
      community.routeros.command:
        commands:
          - /routing ospf interface-template add networks=0.0.0.0/0 area=bbone

    - name: gather all facts
      community.routeros.facts:
        gather_subset: all

    - name: gather ospf instance facts
      debug:
        var: ansible_net_ospf_instance

    - name: gather ospf neighbours
      debug:
        var: ansible_net_ospf_neighbor

